services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      - TZ=Europe/Paris
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/logs:/var/log/postgresql
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      semantop:
        ipv4_address: 172.35.0.2
    restart: always

networks:
  semantop:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.35.0.0/16"
          gateway: "172.35.0.1"
